package com.luispena.droidcafe;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    private static final String TAG = "MyActivity";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                displayMap();
            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        switch (id){
            case R.id.action_order:
                displayToast(getString(R.string.action_order_message));
                return true;

            case R.id.action_status:
                displayToast(getString(R.string.action_status_message));
                return true;

            case R.id.action_favorites:
                displayToast(getString(R.string.action_favorites_message));
                return true;

            case R.id.action_contact:
                displayToast(getString(R.string.action_contact_message));
                return true;

            default:
                Log.d(TAG,"Do nothing ");

        } // end switch

        return super.onOptionsItemSelected(item);
    }

    /**
     *
     *  User Defined Methods for Food ordering
     *  All methods above are generated by basic activity
     *
     */

    public void displayToast(String message) {
        Toast.makeText(getApplicationContext(), message,
                Toast.LENGTH_SHORT).show();
    }



    /**
     * Shows a message that the donut image was clicked.
     */
    public void showDonutOrder(View view) {
        showFoodOrder(getString(R.string.donut_order_message));
    }

    /**
     * Shows a message that the ice cream sandwich image was clicked.
     */
    public void showIceCreamOrder(View view) {
        showFoodOrder(getString(R.string.ice_cream_order_message));
    }

    /**
     * Shows a message that the froyo image was clicked.
     */
    public void showFroyoOrder(View view) {
        showFoodOrder(getString(R.string.froyo_order_message));
    }



    /**
     * Displays a toast message for the food order
     * and starts the OrderActivity activity.
     * @param message   Message to display.
     */
    public void showFoodOrder(String message) {
        displayToast(message);
        Intent intent = new Intent(this, OrderActivity.class);
        startActivity(intent);
    }

    // Function to launch map via the gps icon

    public void displayMap(){

        Intent i = new Intent();
        i.setAction(i.ACTION_VIEW);

        // use the coordinates defined in a string source
        // for the map

        String data = getString(R.string.google_mtv_coord_zoom12);
        i.setData(Uri.parse(data));

        if(i.resolveActivity(getPackageManager()) != null){

            startActivity(i);
        }

    }


}
